// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA_Vj3ccsUdpnicxgVsVbF3aZgaaK8jqA',
    appId: '1:831979072452:web:7b9276d34e70959a2fd291',
    messagingSenderId: '831979072452',
    projectId: 'music-app-th6',
    authDomain: 'music-app-th6.firebaseapp.com',
    storageBucket: 'music-app-th6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtnyffOz1DJrQgop-xP0LiZIgHudP-ibI',
    appId: '1:831979072452:android:39e76a4fdb293a192fd291',
    messagingSenderId: '831979072452',
    projectId: 'music-app-th6',
    storageBucket: 'music-app-th6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR2JDc9cQBTyiUydwpXmsn74-UuRoPl5k',
    appId: '1:831979072452:ios:229e5c3b18f90ff92fd291',
    messagingSenderId: '831979072452',
    projectId: 'music-app-th6',
    storageBucket: 'music-app-th6.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR2JDc9cQBTyiUydwpXmsn74-UuRoPl5k',
    appId: '1:831979072452:ios:229e5c3b18f90ff92fd291',
    messagingSenderId: '831979072452',
    projectId: 'music-app-th6',
    storageBucket: 'music-app-th6.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA_Vj3ccsUdpnicxgVsVbF3aZgaaK8jqA',
    appId: '1:831979072452:web:95e88bf15b42d1512fd291',
    messagingSenderId: '831979072452',
    projectId: 'music-app-th6',
    authDomain: 'music-app-th6.firebaseapp.com',
    storageBucket: 'music-app-th6.firebasestorage.app',
  );

}